image: "python:3.7"

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 --version
  - make dev

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 bild/*.py

unit_test:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pytest --cov=.
