version: "3"

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: sqlco-mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'Chinook'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./volume/mysql:/var/lib/mysql
      - ./db/samples/chinook.sql:/docker-entrypoint-initdb.d/chinook.sql
    ports:
      - "3306:3306"
